### PR TITLE
Fixes #233

### LINKED ISSUE #233: Corretto images use OpenSSL 1.0
It's a bummer that for Corretto, the native part is compiled against OpenSSL 1.0. That leaves quite a gaping hole in SSL support.

Can the native part be built against 1.1 instead?

### PR DESCRIPTION
**Pull request by veselov**
Seems to be that simple.

### CODE REVIEW

**Comment by tianon** [comment]
Unfortunately, @docker-library-bot will revert this if we were to merge it as-is.  A change like this will need to be incorporated into the overall template system to be effective.  Do you know if this would also work on any of the other rpm-based distributions we support?

**Comment by veselov** [comment]
The only other image that uses that, AFAICS, is openjdk-oraclelinux7, right?

**Comment by veselov** [comment]
The latest commit changes the template, and I regenerated to Dockerfiles. Only Corretto images use the YUM packages at this point.

**Comment by tianon** [comment]
Oh, fair enough!  Looks good then :smile:

**Pull request merged**
