### PR TITLE
Disable/move default webapps, per upstream recommendation

### LINKED ISSUE #124: Please provide apline variant without bundled webapps
Alpine image intended to be tiny and light.

For what it frequently use is just provide builds of application with software WARs in [similar way](https://stackoverflow.com/questions/45861951/how-to-remove-root-folder-from-a-docker-container-running-tomcat-base-image/45862361#45862361):
```Dockerfile
FROM tomcat:9-alpine

# Delete existing ROOT folder
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy to images tomcat path
COPY <our application>.war /usr/local/tomcat/webapps/
```

Fist it always require clear webapp folder, and second it may be on 5.5Mb less in size:
```
$ sudo docker run --rm tomcat:9-alpine ls /usr/local/tomcat/webapps/
ROOT
docs
examples
host-manager
manager
$ sudo docker run --rm tomcat:9-alpine du -hs /usr/local/tomcat/webapps/
5.5M    /usr/local/tomcat/webapps/
```

If you wish it may be separate tag like f.e. `9-alpine-empty`.

### PR DESCRIPTION
**Pull request by tianon**
See https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications

Closes #124

### CODE REVIEW

**Comment by tianon** [comment]
**Note:** if you are currently using any of these default webapps, this is a *BREAKING CHANGE* (intentionally).

They are still available within the image under `webapps.dist` and should be trivial to move/symlink/copy back into the `webapps` folder (which is why we're not removing them completely -- the space savings would only be ~7MB, which when compared with the hassle required to add these back, is considered worth it).

**Comment by tianon** [comment]
Thanks to https://github.com/docker-library/official-images/pull/7217 this is now green. :+1:

As an example of one easy way to restore some default example webapp (such as the `manager` applet):

```dockerfile
FROM tomcat:9.0-jdk13-openjdk-oracle
RUN cp -avT $CATALINA_HOME/webapps.dist/manager $CATALINA_HOME/webapps/manager
```

A symlink would probably work as well, although that's untested.

**Comment by brontide** [comment]
For those looking to use the stock image and add manager back in you can do with with an altered entrypoint.  Handy alternative to building a custom image just to have the manager.

```
services:
  tomcat:
    restart: unless-stopped
    image: tomcat:9
    volumes:
      - "./webapps:/usr/local/tomcat/webapps"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
    entrypoint: |
      bash -c 'cp -a webapps.dist/manager webapps/; exec catalina.sh run'
```

**Comment by sezayirdagtekin** [comment]
this is very basic and it doesn't work. interesting

**Pull request merged**
