### PR TITLE
Restructure repo from "X-jreY" to "X/jreY"

### PR DESCRIPTION
**Pull request by tianon**
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)

6.0.45-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0.45: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7

6.0.45-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8

7.0.68-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0.68: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7

7.0.68-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8

8.0.33-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0.33: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
latest: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7

8.0.33-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
```

### CODE REVIEW

**Comment by tianon** [comment]
Again, with the new beta this time:
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)

6.0.45-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0.45: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7

6.0.45-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8

7.0.68-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0.68: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7

7.0.68-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8

8.0.33-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0.33: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
latest: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7

8.0.33-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8

8.5.0-jre8: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5-jre8: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5.0: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
```

**Comment by tianon** [comment]
(this fixes the little annoyance I mentioned in https://github.com/docker-library/tomcat/pull/26#issuecomment-204147865 by giving us an `update.sh` THAT CAN DO BOTH)

**Comment by tianon** [comment]
And now once more with 9.0.0.M4:
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)

6.0.45-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0.45: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7
6: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre7

6.0.45-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8
6-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 6/jre8

7.0.68-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0.68: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7
7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre7

7.0.68-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8
7-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 7/jre8

8.0.33-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8-jre7: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0.33: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8.0: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7
latest: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre7

8.0.33-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8.0-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8
8-jre8: git://github.com/docker-library/tomcat@74b0911f36d776672bc943f9efb05868d1d5d79a 8.0/jre8

8.5.0-jre8: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5-jre8: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5.0: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8
8.5: git://github.com/docker-library/tomcat@82551c9d60c48d35a68b8eb2cc069913be9078ae 8.5/jre8

9.0.0.M4-jre8: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9.0.0-jre8: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9.0-jre8: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9-jre8: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9.0.0.M4: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9.0.0: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9.0: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
9: git://github.com/docker-library/tomcat@92b97a945a2241f868a91d2919e0e7e3f5c84216 9.0/jre8
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
