### PR TITLE
Add Tomcat Native Libraries

### PR DESCRIPTION
**Pull request by tianon**
Closes #19
Closes #23

### CODE REVIEW

**Comment by tianon** [comment]
This isn't ready yet:
```
22-Apr-2016 20:32:36.114 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version 1.1.34 of the APR based Apache Tomcat Native library is installed, while Tomcat requires version 1.2.2
```

Trying to figure out a good way to verify that it actually worked so we can have the build fail (or write a test to verify that it's functioning properly).

**Comment by tianon** [comment]
I've got my fingers crossed -- just pushed an update that _should_ give us some success here.

**Comment by tianon** [comment]
(Travis was all green, but https://github.com/docker-library/official-images/pull/1656 exists now, so I've restarted them :tada:)

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
