### PR TITLE
Add openjdk jre 11 variants for 8.5 and 9.0; Drop tomcat 8.0 (end-of-life)

### LINKED ISSUE #131: OpenJDK 11 support
An OpenJDK 11 / Tomcat 8 / 9 build would be really nice...

### PR DESCRIPTION
**Pull request by yosifkit**
closes #131.

8.0 EOL: https://tomcat.apache.org/tomcat-80-eol.html

### CODE REVIEW

**Comment by ondh** [comment]
good job!
can't wait to use this new version with jre 11.

**Comment by ondh** [comment]
> Why is the jdk11 version not yet listed on dockerhub? =/

I think maybe need to update the generate-stackbrew-library.sh file.
Now I'm using the jdk11 version Dockerfile and build it by myself.

**Comment by dragetd** [comment]
Yes, it looks like this file is only pushing up to version 10 to Dockerhub. Would be awesome if it was updated. :)

**Comment by tianon** [comment]
Good catch, see https://github.com/docker-library/tomcat/commit/185917c653a1a7504e5cc82c0a8ceb6a8a171bc8 and https://github.com/docker-library/official-images/pull/4918. :+1:

**Pull request merged**
