### PR TITLE
Add alpine variants

### LINKED ISSUE #33: alpine tomcat
I use alpine build tomcat image
tomcat image file size 130.7Mb
tomcat version 8.5.3

### PR DESCRIPTION
**Pull request by tianon**
Closes #34
Fixes #33

### CODE REVIEW

**Comment by tianon** [comment]
Depends on https://github.com/docker-library/official-images/pull/1924.

**Comment by yosifkit** [comment]
Doh, `tomcat-hello-world` test assumes `curl` exists in the image.

**Comment by tianon** [comment]
Just kicked off Travis again, given that https://github.com/docker-library/official-images/issues/1929 is merged. :+1:

**Comment by yosifkit** [comment]
GREEEEEN! :green_apple: :green_book: :green_heart: LGTM

**Pull request merged**
