### PR TITLE
loop over keyservers (resolving issue #87)

### LINKED ISSUE #87: Add alternate keyserver mirrors for gpg keys
From what I have observed, `ha.pool.sks-keyservers.net` is not very reliable and I have failed to receive keys on several occasions.

I think we should add alternative mirrors, something like:

```
RUN set -ex; \
	for key in $GPG_KEYS; do \
    gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
    gpg --keyserver keyserver.pgp.com --recv-keys "$key" || \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ; \
	done
```

### PR DESCRIPTION
**Pull request by marcvanandel**
Closes #87

### CODE REVIEW

**Comment by yosifkit** [comment]
My current opinion of this is expressed in https://github.com/docker-library/cassandra/pull/131#issuecomment-358444537.

Related issues: https://github.com/docker-library/mysql/issues/263#issuecomment-354025886 and https://github.com/docker-library/httpd/issues/66#issuecomment-316832441

**Comment by marcvanandel** [comment]
Alright. I do get it. Although the whole keyserver thing is not as stable as we all would like it to be, I do get the point that building in the loop in all images might be too much. And actually the keyserver pool should work properly so we don't have to fix it in an ugly way.

So close the PR?

**Comment by yosifkit** [comment]
Sure, seems sane. Thank you for your understanding.

**Comment by marcvanandel** [comment]
No worries. The best solution is always best ;)

**Pull request closed without merging**
