### PR TITLE
Update for updated OpenJDK base images

### PR DESCRIPTION
**Pull request by tianon**
This is initial adjustments for https://github.com/docker-library/openjdk/pull/322.

FYI to `FROM tomcat` official-images maintainers:

- `convertigo`: @nicolas-albert @opicciotto
- `geonetwork`: @doublebyte1
- `xwiki`: @xwiki (including the last six folks to make PRs in https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fxwiki+is%3Aclosed as well since I don't know if that @ reference will work properly)
  - @evalica
  - @gdelhumeau
  - @surli
  - @vmassol
  - @tmortagne
  - @Enygma2002

### CODE REVIEW

**Comment by vmassol** [comment]
@tianon thanks for the heads up!

So at XWiki we're using `FROM tomcat:8-jre8` which itself was using `FROM openjdk:8-jre`. From what I see in this PR, this hasn't been changed, right? (when I search for `8-jre8` in the PR I don't get a hit).

Anything we should check specifically?

Thanks again

**Comment by tianon** [comment]
@vmassol all "jre" variants of the `tomcat` image are going away because we have to have the JDK to compile Tomcat Native and don't have an easy way to install that temporarily like we did with the Debian-package-based `openjdk:jre` images :disappointed:

**Comment by tianon** [comment]
(that might be something that could change with https://github.com/docker-library/official-images/pull/5929, but as-is it's not something we can commit to right now :disappointed:)

**Comment by vmassol** [comment]
@tianon ok so we need to move from `FROM tomcat:8-jre8` to `FROM tomcat:8-jdk8`. I'll be making the change and send a PR. Thanks

**Comment by nicolas-albert** [comment]
I cannot test anything before Monday. How can we test a tomcat based image based on the AdoptOpenJdk ?

**Comment by tianon** [comment]
@nicolas-albert there aren't any `tomcat` images based on AdoptOpenJDK right now (that's being discussed in https://github.com/docker-library/tomcat/issues/134)

I think the confusion is that the binaries we're using for `openjdk` are _hosted_ by AdoptOpenJDK, but they're not AdoptOpenJDK (they're completely vanilla OpenJDK).

The concrete outcome here for `convertigo` is going to be similar to either what's happening with `xwiki` in https://github.com/docker-library/official-images/pull/5990 (moving to the new `tomcat:jdk` variants and dropping architectures and Alpine variants) or considering https://hub.docker.com/_/adoptopenjdk instead (and thus either waiting for https://github.com/docker-library/tomcat/issues/134 or essentially maintaining your own Tomcat image).

**Pull request merged**
