### PR TITLE
Add "jre9" variants of 8.5 and 9.0

### LINKED ISSUE #100: A tag for jre9
Any plan for support jre9?

### PR DESCRIPTION
**Pull request by tianon**
Closes #100

### CODE REVIEW

**Comment by tianon** [comment]
Doh, `openjdk:9-jre` is based on Sid (where `openjdk-9-*` packages currently live in Debian), but our scripts here all assume Jessie or Stretch. :disappointed:

**Comment by ixtli** [comment]
Just wanted note here that this would be very convenient for me! Is there anyway I could help? Also noted that there doesn't seem to be an `-alpine` version for 9 either :/

**Comment by tianon** [comment]
Regarding Alpine, see https://github.com/docker-library/openjdk/issues/100 and thus https://bugs.alpinelinux.org/issues/8089.

Regarding helping get this merged, we need to figure out a sane way to detect/handle releases newer than Debian Stretch better (or get `openjdk-9` into non-Sid, which is a much taller ask and not something reasonable to expect or wait for).

**Comment by tianon** [comment]
https://github.com/docker-library/tomcat/pull/101/files?w=1#diff-1578307c887a49e90a57418e653ad7f6 is the easiest way to review my current proposed update (which might actually build successfully)

**Comment by ixtli** [comment]
Ok wait so does that merge and subsequent CI build passing mean that someone just needs to add 9.0.2-jre9 to https://github.com/docker-library/official-images/blob/master/library/tomcat ? Perhaps I'm not understanding the CI build spew but it looks like it constructed the image ...

**Comment by yosifkit** [comment]
The CI just tests the image; we still need to make a PR to https://github.com/docker-library/official-images.

**Pull request merged**
